# Generated by Django 2.2.5 on 2019-11-10 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of upload on server'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='body_location',
            field=models.CharField(choices=[('L', 'Left wrist'), ('R', 'Right wrist'), ('O', 'Other')], default='L', max_length=1, verbose_name='body location'),
        ),
    ]
