# Generated by Django 2.2.5 on 2019-12-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191110_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Data path'),
        ),
    ]
