# Generated by Django 2.2.5 on 2019-12-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191204_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdata',
            name='path',
        ),
        migrations.AddField(
            model_name='csvdata',
            name='data',
            field=models.FileField(default='data/dummy.csv', upload_to='data/', verbose_name='data'),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='description',
            field=models.CharField(default='Csv documentation from subject', max_length=255, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='date of upload'),
        ),
    ]
