# Generated by Django 2.2.5 on 2019-12-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191207_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='graph_created',
            field=models.BooleanField(default=0, editable=False, verbose_name='graph image created'),
        ),
    ]
