# Generated by Django 2.2.5 on 2019-12-11 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20191211_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='data',
            field=models.FileField(upload_to='data/', validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
    ]
