# Generated by Django 2.2.5 on 2020-02-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200222_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='fall_asleep',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fall asleep'),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='wake_up',
            field=models.DateTimeField(blank=True, null=True, verbose_name='wake up'),
        ),
    ]
