# Generated by Django 2.2.5 on 2020-02-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200222_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdata',
            name='fall_asleep',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='training_data',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='wake_up',
        ),
    ]
