# Generated by Django 2.2.5 on 2020-02-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200222_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='handedness',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='height',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='weight',
        ),
    ]
