# Generated by Django 2.2.5 on 2020-02-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200222_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psdata',
            old_name='subject',
            new_name='csv_data',
        ),
    ]
