# Generated by Django 3.0.3 on 2020-09-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20200510_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepDiaryDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('day_sleep_count', models.PositiveSmallIntegerField(verbose_name='count of sleep during day')),
                ('day_sleep_time', models.TimeField(verbose_name='duration of sleep during day')),
                ('alcohol_count', models.PositiveSmallIntegerField(verbose_name='number of alcoholic beverages')),
                ('alcohol_time', models.TimeField(verbose_name='time of the last alcoholic beverage')),
                ('caffeine_count', models.PositiveSmallIntegerField(verbose_name='number of caffeine drinks')),
                ('caffeine_time', models.TimeField(verbose_name='time of the last caffeine drink')),
                ('sleeping_pill', models.BooleanField(verbose_name='sleeping pill')),
                ('bed_time', models.TimeField(verbose_name='bed time')),
                ('sleep_time', models.TimeField(verbose_name='try to fall asleep time')),
                ('sleep_duration', models.TimeField(verbose_name='how long it took to fall asleep')),
                ('wake_count', models.PositiveSmallIntegerField(verbose_name='number of wake ups during night')),
                ('wake_time', models.TimeField(verbose_name='wake up time')),
                ('get_up_time', models.TimeField(verbose_name='get up time')),
                ('sleep_quality', models.PositiveSmallIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Fair'), (4, 'Good'), (5, 'Very good')], verbose_name='sleep quality')),
                ('rest_quality', models.PositiveSmallIntegerField(choices=[(1, 'Not at all rested'), (2, 'Slightly rested'), (3, 'Somehow rested'), (4, 'Well-rested'), (5, 'Very well-rested')], verbose_name='rest quality')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='WakeInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='start')),
                ('end', models.TimeField(verbose_name='stop')),
                ('sleep_diary_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SleepDiaryDay')),
            ],
        ),
    ]
