# Generated by Django 3.1.1 on 2020-12-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_sleepdiaryday_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBDSQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField(verbose_name='1. i sometimes have very vivid dreams')),
                ('q2', models.BooleanField(verbose_name='2. my dreams frequently have aggressive or action packed content')),
                ('q3', models.BooleanField(verbose_name='3. the dream contents mostly match my nocturnal behaviour')),
                ('q4', models.BooleanField(verbose_name='4. i know that my arms or legs move when i sleep')),
                ('q5', models.BooleanField(verbose_name='5. it thereby happened that i (almost) hurt my bed partner or myself')),
                ('q61', models.BooleanField(verbose_name='6.1. i have or had the following phenomena during my dreams: speaking, shouting, swearing, laughing loudly')),
                ('q62', models.BooleanField(verbose_name='6.2. i have or had the following phenomena during my dreams: sudden limb movements, "fights"')),
                ('q63', models.BooleanField(verbose_name='6.1. i have or had the following phenomena during my dreams: gestures, complex movements, that are useless during sleep, e.g., to wave, to salute, to frighten mosquitoes, falls off the bed')),
                ('q64', models.BooleanField(verbose_name='i have or had the following phenomena during my dreams: things that fell down around the bed, e.g., bedside lamp, book, glasses')),
                ('q7', models.BooleanField(verbose_name='7. it happens that my movements awake me')),
                ('q8', models.BooleanField(verbose_name='8. after awakening i mostly remember the content of my dreams well')),
                ('q9', models.BooleanField(verbose_name='9. my sleep is frequently disturbed')),
                ('q10', models.BooleanField(verbose_name='10. i have/had a disease of the nervous system (e.g., stroke, head trauma, parkinsonism, RLS, narcolepsy, depression, epilepsy, inflammatory disease of the brain), which?')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subject')),
            ],
        ),
    ]
