# Generated by Django 3.1.1 on 2020-12-17 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20201217_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbdsq',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rbdsq',
            name='q10comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='which?'),
        ),
        migrations.AddField(
            model_name='sleepdiaryday',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date of upload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wakeinterval',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rbdsq',
            name='q1',
            field=models.BooleanField(verbose_name='1. I sometimes have very vivid dreams.'),
        ),
        migrations.AlterField(
            model_name='rbdsq',
            name='q10',
            field=models.BooleanField(verbose_name='10. I have/had a disease of the nervous system (e.g., stroke, head trauma, parkinsonism, RLS, narcolepsy, depression, epilepsy, inflammatory disease of the brain),'),
        ),
        migrations.AlterField(
            model_name='rbdsq',
            name='q2',
            field=models.BooleanField(verbose_name='2. My dreams frequently have aggressive or action packed content.'),
        ),
        migrations.AlterField(
            model_name='rbdsq',
            name='q3',
            field=models.BooleanField(verbose_name='3. The dream contents mostly match my nocturnal behaviour.'),
        ),
        migrations.AlterField(
            model_name='rbdsq',
            name='q4',
            field=models.BooleanField(verbose_name='4. I know that my arms or legs move when I sleep.'),
        ),
        migrations.AlterField(
            model_name='rbdsq',
            name='q5',
            field=models.BooleanField(verbose_name='5. It thereby happened that I (almost) hurt my bed partner or myself.'),
        ),
        migrations.AlterField(
            model_name='rbdsq',
            name='q61',
            field=models.BooleanField(verbose_name='6.1. I have or had the following phenomena during my dreams: speaking, shouting, swearing, laughing loudly.'),
        ),
        migrations.AlterField(
            model_name='rbdsq',
            name='q62',
            field=models.BooleanField(verbose_name='6.2. I have or had the following phenomena during my dreams: sudden limb movements, "fights".'),
        ),
        migrations.AlterField(
            model_name='rbdsq',
            name='q63',
            field=models.BooleanField(verbose_name='6.3. I have or had the following phenomena during my dreams: gestures, complex movements, that are useless during sleep, e.g., to wave, to salute, to frighten mosquitoes, falls off the bed.'),
        ),
        migrations.AlterField(
            model_name='rbdsq',
            name='q64',
            field=models.BooleanField(verbose_name='6.4 I have or had the following phenomena during my dreams: things that fell down around the bed, e.g., bedside lamp, book, glasses.'),
        ),
        migrations.AlterField(
            model_name='rbdsq',
            name='q7',
            field=models.BooleanField(verbose_name='7. It happens that my movements awake me.'),
        ),
        migrations.AlterField(
            model_name='rbdsq',
            name='q8',
            field=models.BooleanField(verbose_name='8. After awakening I mostly remember the content of my dreams well.'),
        ),
        migrations.AlterField(
            model_name='rbdsq',
            name='q9',
            field=models.BooleanField(verbose_name='9. My sleep is frequently disturbed.'),
        ),
    ]
