# Generated by Django 3.1.1 on 2020-12-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0035_auto_20201226_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepnight',
            name='end',
            field=models.DateTimeField(verbose_name='end'),
        ),
    ]
