# Generated by Django 3.1.1 on 2021-10-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0040_sleepnight_awk5plus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleepnight',
            name='se',
        ),
        migrations.RemoveField(
            model_name='sleepnight',
            name='sf',
        ),
        migrations.RemoveField(
            model_name='sleepnight',
            name='tst',
        ),
        migrations.AddField(
            model_name='sleepnight',
            name='tib',
            field=models.PositiveIntegerField(default=0, verbose_name='time in bed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleepnight',
            name='wasf',
            field=models.PositiveIntegerField(default=0, verbose_name='wake after sleep offset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleepnight',
            name='wb',
            field=models.PositiveIntegerField(default=0, verbose_name='wake bouts'),
            preserve_default=False,
        ),
    ]
