# Generated by Django 3.1.1 on 2021-12-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0041_auto_20211002_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='diagnosis',
            field=models.CharField(choices=[('NA', 'Healthy Control'), ('pPD', 'Probable Parkinson Disease'),
                                            ('pMCI', 'Probable Mild Cognitive Impairment'),
                                            ('HC', 'Hemicrania Continua'), ('SA', 'Sleep Apnea')], default='NA',
                                   max_length=255, verbose_name='diagnosis'),
        ),
    ]
