# Generated by Django 3.1.1 on 2021-12-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0042_auto_20211204_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='subject',
            name='HC',
            field=models.BooleanField(default=False, verbose_name='Hemicrania Continua'),
        ),
        migrations.AddField(
            model_name='subject',
            name='SA',
            field=models.BooleanField(default=False, verbose_name='Sleep Apnea'),
        ),
        migrations.AddField(
            model_name='subject',
            name='pMCI',
            field=models.BooleanField(default=False, verbose_name='Probable Mild Cognitive Impairment'),
        ),
        migrations.AddField(
            model_name='subject',
            name='pPD',
            field=models.BooleanField(default=False, verbose_name='Probable Parkinson Disease'),
        ),
    ]
