# Generated by Django 3.1.1 on 2021-12-04 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0043_auto_20211204_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='sleep_disorder',
        ),
    ]
