# Generated by Django 3.1.1 on 2022-04-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0044_remove_subject_sleep_disorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdata',
            name='data_cached',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='features_extracted',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='prediction_cached',
        ),
        migrations.AlterField(
            model_name='subject',
            name='HC',
            field=models.BooleanField(default=False, verbose_name='hemicrania continua'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='SA',
            field=models.BooleanField(default=False, verbose_name='sleep apnea'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pMCI',
            field=models.BooleanField(default=False, verbose_name='probable mild cognitive impairment'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pPD',
            field=models.BooleanField(default=False, verbose_name='probable parkinson disease'),
        ),
    ]
