# Generated by Django 3.1.1 on 2022-04-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0045_auto_20220402_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='HC',
            field=models.BooleanField(default=False, verbose_name='healthy control'),
        ),
    ]
