# Generated by Django 3.1.1 on 2022-04-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0046_auto_20220402_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='predPDorMCI',
            field=models.BooleanField(default=False, verbose_name='probable parkinson disease'),
        ),
    ]
