# Generated by Django 4.1.2 on 2022-10-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0047_subject_predpdormci'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='diagnosis',
            field=models.CharField(choices=[('D', 'preDLB'), ('N', 'NonHC'), ('H', 'HC'), ('U', 'Unknown')],
                                   default='U', max_length=1, verbose_name='diagnosis'),
        ),
    ]
