# Generated by Django 3.1.14 on 2024-07-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0048_subject_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date to process'),
        ),
    ]
