# Generated by Django 3.1.14 on 2024-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0049_csvdata_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end date to process'),
        ),
    ]
