# Generated by Django 3.1.14 on 2024-09-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0051_sleeppydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepnight',
            name='broken',
            field=models.BooleanField(default=False, verbose_name='broken according to sleepy'),
        ),
    ]
