# Generated by Django 3.1.14 on 2024-09-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0052_sleepnight_broken'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeppydata',
            name='broken',
            field=models.BooleanField(default=False, verbose_name='broken according to sleep nights'),
        ),
    ]
