# Generated by Django 3.1.14 on 2024-10-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0054_signalfeatures_sleepnightactivityindexfeatures_sleeppyactivityindexfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='diagnosis2024',
            field=models.CharField(choices=[('D', 'preDLB'), ('N', 'NonHC'), ('H', 'HC'), ('U', 'Unknown')],
                                   default='U', max_length=1, verbose_name='diagnosis'),
        ),
    ]
