# Generated by Django 4.1.2 on 2025-07-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0055_subject_diagnosis2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='dreamt_data',
            field=models.BooleanField(default=False, verbose_name='dreamt data'),
        ),
    ]
