# Generated by Django 5.2.6 on 2026-01-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0056_csvdata_dreamt_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='diagnosis_code',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(3, 'preDLB'), (2, 'MCI-AD'), (1, 'NonHC'), (0, 'HC')],
                                                   null=True, verbose_name='diagnosis code'),
        ),
    ]
