# Generated by Django 5.2.6 on 2026-05-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0057_subject_diagnosis_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='attention',
            field=models.FloatField(blank=True, null=True, verbose_name='Attention'),
        ),
        migrations.AddField(
            model_name='subject',
            name='executive',
            field=models.FloatField(blank=True, null=True, verbose_name='Executive'),
        ),
        migrations.AddField(
            model_name='subject',
            name='mfs',
            field=models.FloatField(blank=True, null=True, verbose_name='MFS'),
        ),
        migrations.AddField(
            model_name='subject',
            name='rbdq',
            field=models.FloatField(blank=True, null=True, verbose_name='RBDq'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updrs',
            field=models.FloatField(blank=True, null=True, verbose_name='UPDRS'),
        ),
        migrations.AddField(
            model_name='subject',
            name='visuospatial',
            field=models.FloatField(blank=True, null=True, verbose_name='Visuospatial'),
        ),
    ]
