# Generated by Django 5.2.6 on 2026-06-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0058_subject_attention_subject_executive_subject_mfs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='education_years',
            field=models.FloatField(blank=True, null=True, verbose_name='Education (years)'),
        ),
    ]
