# -*- coding: utf-8 -*-
"""prototyping_cls.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zbsS4g1ZPagFJSh48hl5EWivq9hOSNi9
"""

# Dependencies
# pip install numpy
# pip install pandas
# pip install matplotlib
# pip install xlrd
# pip install openpyxl
# pip install sklearn
# pip install xgboost
