# Generated by Django 2.2.5 on 2019-11-09 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='subject code')),
                ('body_location', models.CharField(choices=[('L', 'Left wrist'), ('R', 'Right wrist'), ('O', 'Other')], default='LW', max_length=1, verbose_name='body location')),
                ('birth', models.DateField(verbose_name='date of birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='sex')),
                ('height', models.SmallIntegerField(verbose_name='height (cm)')),
                ('weight', models.SmallIntegerField(verbose_name='weight (kg)')),
                ('handedness', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='R', max_length=1, verbose_name='handedness')),
            ],
        ),
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(verbose_name='data path')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Subject')),
            ],
        ),
    ]
