# Generated by Django 2.2.5 on 2019-12-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191207_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='birth',
        ),
        migrations.AddField(
            model_name='subject',
            name='age',
            field=models.SmallIntegerField(default=24, verbose_name='age (years)'),
            preserve_default=False,
        ),
    ]
