# Generated by Django 2.2.5 on 2019-12-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20191207_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='graph_created',
            field=models.BooleanField(default=0, editable=False, verbose_name='graph image created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='data',
            field=models.FileField(upload_to='data/', verbose_name='data'),
        ),
    ]
