# Generated by Django 2.2.5 on 2019-12-11 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20191207_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='description',
            field=models.CharField(max_length=255, validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='description'),
        ),
    ]
