# Generated by Django 2.2.5 on 2019-12-14 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20191211_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='body_location',
        ),
        migrations.AddField(
            model_name='csvdata',
            name='body_location',
            field=models.CharField(choices=[('L', 'Left wrist'), ('R', 'Right wrist'), ('O', 'Other')], default='L', max_length=1, verbose_name='body location'),
        ),
        migrations.AddField(
            model_name='subject',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='subject code'),
        ),
    ]
