# Generated by Django 2.2.5 on 2020-02-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20191214_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='fall_asleep',
            field=models.DateField(blank=True, null=True, verbose_name='fall asleep'),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='training_data',
            field=models.BooleanField(default=False, verbose_name='training data'),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='wake_up',
            field=models.DateField(blank=True, null=True, verbose_name='wake up'),
        ),
    ]
