# Generated by Django 2.2.5 on 2020-02-22 20:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200222_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsData',
            fields=[
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.Subject')),
                ('data', models.FileField(upload_to='ps/', validators=[django.core.validators.FileExtensionValidator(['txt'])], verbose_name='data')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='date of upload')),
                ('graph_created', models.BooleanField(default=0, editable=False, verbose_name='graph image created')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, verbose_name='diagnosis'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sleep_disorder',
            field=models.BooleanField(default=False, verbose_name='sleep disorder'),
        ),
    ]
