# Generated by Django 2.2.5 on 2020-02-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200222_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psdata',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.CsvData'),
        ),
    ]
