# Generated by Django 2.2.5 on 2020-03-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20200226_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='full_data',
            field=models.BooleanField(default=False, verbose_name='full data'),
        ),
    ]
