# Generated by Django 3.0.4 on 2020-03-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_csvdata_full_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psdata',
            name='data_cached',
        ),
    ]
