# Generated by Django 3.0.4 on 2020-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0020_remove_psdata_data_cached'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='features_extracted',
            field=models.BooleanField(default=0, editable=False, verbose_name='features extracted'),
        ),
    ]
