# Generated by Django 3.1.1 on 2020-09-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20200927_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepdiaryday',
            name='alcohol_time',
            field=models.TimeField(blank=True, null=True, verbose_name='time of the last alcoholic beverage'),
        ),
        migrations.AlterField(
            model_name='sleepdiaryday',
            name='caffeine_time',
            field=models.TimeField(blank=True, null=True, verbose_name='time of the last caffeine drink'),
        ),
        migrations.AlterField(
            model_name='sleepdiaryday',
            name='day_sleep_time',
            field=models.TimeField(blank=True, null=True, verbose_name='duration of sleep during day'),
        ),
        migrations.AlterField(
            model_name='sleepdiaryday',
            name='rest_quality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Not at all rested'), (2, 'Slightly rested'), (3, 'Somehow rested'), (4, 'Well-rested'), (5, 'Very well-rested')], null=True, verbose_name='rest quality'),
        ),
        migrations.AlterField(
            model_name='sleepdiaryday',
            name='sleep_quality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Fair'), (4, 'Good'), (5, 'Very good')], null=True, verbose_name='sleep quality'),
        ),
    ]
