# Generated by Django 3.1.1 on 2020-12-26 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0032_sleepnight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepnight',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sleepdiaryday'),
        ),
    ]
