# Generated by Django 3.1.1 on 2020-12-26 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0033_auto_20201226_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleepnight',
            old_name='data',
            new_name='diary_day',
        ),
    ]
